version: '3'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=TEST
      - AWS_SECRET_ACCESS_KEY=TEST
    ports:
      - '4566:4566'